import { Navigation } from '../components/Navigation'
import '../styles/globals.css'

export const metadata = {
  title: 'My first web app with Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>{metadata.title}</title>
        <meta name='description' content={metadata.description} />
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
